// This file is auto-generated by @hey-api/openapi-ts

export const protobufAnySchema = {
  type: "object",
  properties: {
    "@type": {
      type: "string",
    },
  },
  additionalProperties: {},
} as const

export const rpcStatusSchema = {
  type: "object",
  properties: {
    code: {
      type: "integer",
      format: "int32",
    },
    message: {
      type: "string",
    },
    details: {
      type: "array",
      items: {
        $ref: "#/components/schemas/protobufAny",
      },
    },
  },
} as const

export const v1GetRegionsRequestSchema = {
  type: "object",
  properties: {
    regions: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const

export const v1GetRegionsResponseSchema = {
  type: "object",
  properties: {
    regions: {
      type: "array",
      items: {
        $ref: "#/components/schemas/v1RegionInfo",
      },
    },
  },
} as const

export const v1RegionInfoSchema = {
  type: "object",
  properties: {
    region: {
      type: "string",
    },
    countryCode: {
      type: "integer",
      format: "int32",
    },
    supported: {
      type: "boolean",
    },
  },
} as const
