// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PublicServiceGetRegionsData, PublicServiceGetRegionsResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1GetRegionsResponse A successful response.
 * @throws ApiError
 */
export const publicServiceGetRegions = (data: PublicServiceGetRegionsData): CancelablePromise<PublicServiceGetRegionsResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/public/regions',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};