// This file is auto-generated by @hey-api/openapi-ts

export type protobufAny = {
  "@type"?: string
  [key: string]: (unknown | string) | undefined
}

export type rpcStatus = {
  code?: number
  message?: string
  details?: Array<protobufAny>
}

export type v1GetRegionsRequest = {
  regions?: Array<string>
}

export type v1GetRegionsResponse = {
  regions?: Array<v1RegionInfo>
}

export type v1RegionInfo = {
  region?: string
  countryCode?: number
  supported?: boolean
}

export type PublicServiceGetRegionsData = {
  requestBody: v1GetRegionsRequest
}

export type PublicServiceGetRegionsResponse = v1GetRegionsResponse
