// This file is auto-generated by @hey-api/openapi-ts

export const BillingServiceHandleWebhookBodySchema = {
    type: 'object',
    properties: {
        payload: {
            type: 'string',
            format: 'byte'
        },
        signature: {
            type: 'string'
        }
    }
} as const;

export const BillingServiceRefreshPaymentStatusBodySchema = {
    type: 'object',
    properties: {
        provider: {
            '$ref': '#/components/schemas/v1Provider'
        }
    }
} as const;

export const protobufAnySchema = {
    type: 'object',
    properties: {
        '@type': {
            type: 'string'
        }
    },
    additionalProperties: {}
} as const;

export const rpcStatusSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        message: {
            type: 'string'
        },
        details: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/protobufAny'
            }
        }
    }
} as const;

export const v1CheckDailySubscriptionsResponseSchema = {
    type: 'object',
    properties: {
        updated: {
            type: 'integer',
            format: 'int32'
        },
        expired: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const v1CreateCheckoutSessionRequestSchema = {
    type: 'object',
    properties: {
        priceId: {
            type: 'string'
        },
        successUrl: {
            type: 'string'
        },
        cancelUrl: {
            type: 'string'
        }
    }
} as const;

export const v1CreateCheckoutSessionResponseSchema = {
    type: 'object',
    properties: {
        url: {
            type: 'string'
        },
        sessionId: {
            type: 'string'
        }
    }
} as const;

export const v1CreateDokuPaymentRequestSchema = {
    type: 'object',
    properties: {
        amountIdr: {
            type: 'string',
            format: 'int64',
            title: 'IDR amount without decimals'
        },
        invoiceNumber: {
            type: 'string'
        },
        paymentDueMinutes: {
            type: 'integer',
            format: 'int32',
            title: 'default 60 if not provided'
        }
    }
} as const;

export const v1CreateDokuPaymentResponseSchema = {
    type: 'object',
    properties: {
        paymentUrl: {
            type: 'string'
        },
        transactionId: {
            type: 'string'
        }
    }
} as const;

export const v1GetSubscriptionStatusResponseSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string'
        },
        stripeSubscriptionId: {
            type: 'string'
        },
        currentPeriodEnd: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const v1PaymentStatusResponseSchema = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        },
        provider: {
            '$ref': '#/components/schemas/v1Provider'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const v1ProviderSchema = {
    type: 'string',
    enum: ['PROVIDER_UNSPECIFIED', 'PROVIDER_STRIPE', 'PROVIDER_DOKU'],
    default: 'PROVIDER_UNSPECIFIED'
} as const;