// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { BillingServiceCreateCheckoutSessionData, BillingServiceCreateCheckoutSessionResponse, BillingServiceCreateDokuPaymentData, BillingServiceCreateDokuPaymentResponse, BillingServiceRefreshPaymentStatusData, BillingServiceRefreshPaymentStatusResponse, BillingServiceGetSubscriptionStatusResponse, BillingServiceCheckDailySubscriptionsResponse, BillingServiceHandleWebhookData, BillingServiceHandleWebhookResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1CreateCheckoutSessionResponse A successful response.
 * @throws ApiError
 */
export const billingServiceCreateCheckoutSession = (data: BillingServiceCreateCheckoutSessionData): CancelablePromise<BillingServiceCreateCheckoutSessionResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/billing/checkout',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * Initiate DOKU Jokul payment and return payment URL
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1CreateDokuPaymentResponse A successful response.
 * @throws ApiError
 */
export const billingServiceCreateDokuPayment = (data: BillingServiceCreateDokuPaymentData): CancelablePromise<BillingServiceCreateDokuPaymentResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/billing/doku/payment',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * Refresh payment status by provider and transaction id
 * @param data The data for the request.
 * @param data.transactionId
 * @param data.requestBody
 * @returns v1PaymentStatusResponse A successful response.
 * @throws ApiError
 */
export const billingServiceRefreshPaymentStatus = (data: BillingServiceRefreshPaymentStatusData): CancelablePromise<BillingServiceRefreshPaymentStatusResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/billing/payments/{transactionId}/refresh',
        path: {
            transactionId: data.transactionId
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @returns v1GetSubscriptionStatusResponse A successful response.
 * @throws ApiError
 */
export const billingServiceGetSubscriptionStatus = (): CancelablePromise<BillingServiceGetSubscriptionStatusResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/v1/billing/subscription',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * Daily subscriptions check (cron-triggered)
 * @returns v1CheckDailySubscriptionsResponse A successful response.
 * @throws ApiError
 */
export const billingServiceCheckDailySubscriptions = (): CancelablePromise<BillingServiceCheckDailySubscriptionsResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/billing/subscriptions/check',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.provider
 * @param data.requestBody
 * @returns unknown A successful response.
 * @throws ApiError
 */
export const billingServiceHandleWebhook = (data: BillingServiceHandleWebhookData): CancelablePromise<BillingServiceHandleWebhookResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/billing/webhook/{provider}',
        path: {
            provider: data.provider
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};