// This file is auto-generated by @hey-api/openapi-ts

export type BillingServiceHandleWebhookBody = {
  payload?: string
  signature?: string
}

export type BillingServiceRefreshPaymentStatusBody = {
  provider?: v1Provider
}

export type protobufAny = {
  "@type"?: string
  [key: string]: (unknown | string) | undefined
}

export type rpcStatus = {
  code?: number
  message?: string
  details?: Array<protobufAny>
}

export type v1CheckDailySubscriptionsResponse = {
  updated?: number
  expired?: number
}

export type v1CreateCheckoutSessionRequest = {
  priceId?: string
  successUrl?: string
  cancelUrl?: string
}

export type v1CreateCheckoutSessionResponse = {
  url?: string
  sessionId?: string
}

export type v1CreateDokuPaymentRequest = {
  amountIdr?: string
  invoiceNumber?: string
  paymentDueMinutes?: number
}

export type v1CreateDokuPaymentResponse = {
  paymentUrl?: string
  transactionId?: string
}

export type v1GetSubscriptionStatusResponse = {
  status?: string
  stripeSubscriptionId?: string
  currentPeriodEnd?: string
}

export type v1PaymentStatusResponse = {
  transactionId?: string
  provider?: v1Provider
  status?: string
}

export type v1Provider =
  | "PROVIDER_UNSPECIFIED"
  | "PROVIDER_STRIPE"
  | "PROVIDER_DOKU"

export type BillingServiceCreateCheckoutSessionData = {
  requestBody: v1CreateCheckoutSessionRequest
}

export type BillingServiceCreateCheckoutSessionResponse =
  v1CreateCheckoutSessionResponse

export type BillingServiceCreateDokuPaymentData = {
  requestBody: v1CreateDokuPaymentRequest
}

export type BillingServiceCreateDokuPaymentResponse =
  v1CreateDokuPaymentResponse

export type BillingServiceRefreshPaymentStatusData = {
  requestBody: BillingServiceRefreshPaymentStatusBody
  transactionId: string
}

export type BillingServiceRefreshPaymentStatusResponse = v1PaymentStatusResponse

export type BillingServiceGetSubscriptionStatusResponse =
  v1GetSubscriptionStatusResponse

export type BillingServiceCheckDailySubscriptionsResponse =
  v1CheckDailySubscriptionsResponse

export type BillingServiceHandleWebhookData = {
  provider: "PROVIDER_UNSPECIFIED" | "PROVIDER_STRIPE" | "PROVIDER_DOKU"
  requestBody: BillingServiceHandleWebhookBody
}

export type BillingServiceHandleWebhookResponse = {
  [key: string]: unknown
}
