// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  meta: ListMeta
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type ListMeta = {
  count: number
  page?: number | null
  page_size?: number | null
  total?: number | null
  has_next?: boolean | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * Payload used when creating a new role.
 */
export type RoleCreate = {
  /**
   * System role name
   */
  name: RoleEnum
}

export type RoleEnum = "customer" | "salon_owner" | "employee" | "superuser"

export type RolePublic = {
  /**
   * System role name
   */
  name: RoleEnum
  id: number
}

export type RolesPublic = {
  data: Array<RolePublic>
  meta: ListMeta
}

export type RoleUpdate = {
  name: RoleEnum
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email?: string | null
  phone_number?: string | null
  is_active?: boolean
  is_email_verified?: boolean
  is_phone_verified?: boolean
  is_totp_enabled?: boolean
  totp_secret?: string | null
  full_name?: string | null
  roles?: Array<RoleEnum>
  password: string
}

export type UserPublic = {
  email?: string | null
  phone_number?: string | null
  is_active?: boolean
  is_email_verified?: boolean
  is_phone_verified?: boolean
  is_totp_enabled?: boolean
  totp_secret?: string | null
  full_name?: string | null
  roles?: Array<RoleEnum>
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  meta: ListMeta
}

export type UserUpdate = {
  email?: string | null
  phone_number?: string | null
  is_active?: boolean
  is_email_verified?: boolean
  is_phone_verified?: boolean
  is_totp_enabled?: boolean
  totp_secret?: string | null
  full_name?: string | null
  roles?: Array<RoleEnum>
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type RolesListRolesData = {
  limit?: number
  skip?: number
}

export type RolesListRolesResponse = RolesPublic

export type RolesCreateRoleData = {
  requestBody: RoleCreate
}

export type RolesCreateRoleResponse = RolePublic

export type RolesGetRoleData = {
  roleId: string
}

export type RolesGetRoleResponse = RolePublic

export type RolesUpdateRoleData = {
  requestBody: RoleUpdate
  roleId: string
}

export type RolesUpdateRoleResponse = RolePublic

export type RolesDeleteRoleData = {
  roleId: string
}

export type RolesDeleteRoleResponse = Message

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
