// This file is auto-generated by @hey-api/openapi-ts

export const protobufAnySchema = {
    type: 'object',
    properties: {
        '@type': {
            type: 'string'
        }
    },
    additionalProperties: {}
} as const;

export const rpcStatusSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        message: {
            type: 'string'
        },
        details: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/protobufAny'
            }
        }
    }
} as const;

export const v1AddEmailRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        }
    }
} as const;

export const v1AddEmailResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1AddPhoneNumberRequestSchema = {
    type: 'object',
    properties: {
        phoneNumber: {
            type: 'string'
        },
        region: {
            type: 'string'
        }
    }
} as const;

export const v1AddPhoneNumberResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1AdminUpdateUserRequestSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string'
        },
        fullName: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        isActive: {
            type: 'boolean'
        }
    }
} as const;

export const v1AdminUpdateUserResponseSchema = {
    type: 'object',
    properties: {
        user: {
            '$ref': '#/components/schemas/v1User'
        }
    }
} as const;

export const v1CreateUserRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        fullName: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        isActive: {
            type: 'boolean'
        }
    }
} as const;

export const v1CreateUserResponseSchema = {
    type: 'object',
    properties: {
        user: {
            '$ref': '#/components/schemas/v1User'
        }
    }
} as const;

export const v1GetUserResponseSchema = {
    type: 'object',
    properties: {
        user: {
            '$ref': '#/components/schemas/v1User'
        }
    }
} as const;

export const v1ListUsersResponseSchema = {
    type: 'object',
    properties: {
        users: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/v1User'
            }
        },
        total: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const v1LoginUserRequestSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const v1LoginUserResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        },
        refreshExpiresAt: {
            type: 'string',
            format: 'date-time'
        },
        tokenType: {
            type: 'string'
        }
    }
} as const;

export const v1LoginWithPhoneRequestSchema = {
    type: 'object',
    properties: {
        phoneNumber: {
            type: 'string'
        },
        otpCode: {
            type: 'string'
        },
        region: {
            type: 'string'
        }
    }
} as const;

export const v1LoginWithPhoneResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        },
        refreshExpiresAt: {
            type: 'string',
            format: 'date-time'
        },
        tokenType: {
            type: 'string'
        }
    }
} as const;

export const v1RecoverPasswordRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        }
    },
    title: 'Password recovery and reset messages'
} as const;

export const v1RecoverPasswordResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1RefreshTokenRequestSchema = {
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string'
        }
    }
} as const;

export const v1RefreshTokenResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const v1RegisterPhoneUserRequestSchema = {
    type: 'object',
    properties: {
        phoneNumber: {
            type: 'string'
        },
        fullName: {
            type: 'string'
        },
        region: {
            type: 'string'
        }
    }
} as const;

export const v1RegisterPhoneUserResponseSchema = {
    type: 'object',
    properties: {
        verificationToken: {
            type: 'string'
        }
    }
} as const;

export const v1RequestPhoneOTPRequestSchema = {
    type: 'object',
    properties: {
        phoneNumber: {
            type: 'string'
        },
        region: {
            type: 'string'
        }
    }
} as const;

export const v1RequestPhoneOTPResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1ResendEmailVerificationRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        }
    }
} as const;

export const v1ResendEmailVerificationResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1ResetPasswordRequestSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string'
        },
        newPassword: {
            type: 'string'
        }
    }
} as const;

export const v1ResetPasswordResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1UpdateUserRequestSchema = {
    type: 'object',
    properties: {
        fullName: {
            type: 'string'
        },
        previousPassword: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const v1UpdateUserResponseSchema = {
    type: 'object',
    properties: {
        user: {
            '$ref': '#/components/schemas/v1User'
        }
    }
} as const;

export const v1UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        phoneNumber: {
            type: 'string'
        },
        fullName: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        isEmailVerified: {
            type: 'boolean'
        },
        isPhoneVerified: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const v1VerifyAddEmailOTPRequestSchema = {
    type: 'object',
    properties: {
        otpCode: {
            type: 'string'
        }
    }
} as const;

export const v1VerifyAddEmailOTPResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1VerifyAddPhoneOTPRequestSchema = {
    type: 'object',
    properties: {
        otpCode: {
            type: 'string'
        },
        region: {
            type: 'string'
        }
    }
} as const;

export const v1VerifyAddPhoneOTPResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1VerifyEmailOTPRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        otpCode: {
            type: 'string'
        }
    }
} as const;

export const v1VerifyEmailOTPResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const v1VerifyPhoneOTPRequestSchema = {
    type: 'object',
    properties: {
        phoneNumber: {
            type: 'string'
        },
        otpCode: {
            type: 'string'
        },
        region: {
            type: 'string'
        }
    }
} as const;

export const v1VerifyPhoneOTPResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        },
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        },
        refreshExpiresAt: {
            type: 'string',
            format: 'date-time'
        },
        tokenType: {
            type: 'string'
        }
    }
} as const;