// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { UserServiceAdminUpdateUserData, UserServiceAdminUpdateUserResponse, UserServiceLoginUserData, UserServiceLoginUserResponse, UserServiceLoginWithPhoneData, UserServiceLoginWithPhoneResponse, UserServiceRefreshTokenData, UserServiceRefreshTokenResponse, UserServiceRecoverPasswordData, UserServiceRecoverPasswordResponse, UserServiceResetPasswordData, UserServiceResetPasswordResponse, UserServiceGetUserResponse, UserServiceCreateUserData, UserServiceCreateUserResponse, UserServiceUpdateUserData, UserServiceUpdateUserResponse, UserServiceAddEmailData, UserServiceAddEmailResponse, UserServiceAddPhoneNumberData, UserServiceAddPhoneNumberResponse, UserServiceRegisterPhoneUserData, UserServiceRegisterPhoneUserResponse, UserServiceRequestPhoneOtpData, UserServiceRequestPhoneOtpResponse, UserServiceResendEmailVerificationData, UserServiceResendEmailVerificationResponse, UserServiceVerifyAddEmailOtpData, UserServiceVerifyAddEmailOtpResponse, UserServiceVerifyAddPhoneOtpData, UserServiceVerifyAddPhoneOtpResponse, UserServiceVerifyEmailOtpData, UserServiceVerifyEmailOtpResponse, UserServiceVerifyPhoneOtpData, UserServiceVerifyPhoneOtpResponse, UserServiceListUsersData, UserServiceListUsersResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1AdminUpdateUserResponse A successful response.
 * @throws ApiError
 */
export const userServiceAdminUpdateUser = (data: UserServiceAdminUpdateUserData): CancelablePromise<UserServiceAdminUpdateUserResponse> => {
    return __request(OpenAPI, {
        method: 'PUT',
        url: '/v1/admin/user',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1LoginUserResponse A successful response.
 * @throws ApiError
 */
export const userServiceLoginUser = (data: UserServiceLoginUserData): CancelablePromise<UserServiceLoginUserResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/login/access-token',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1LoginWithPhoneResponse A successful response.
 * @throws ApiError
 */
export const userServiceLoginWithPhone = (data: UserServiceLoginWithPhoneData): CancelablePromise<UserServiceLoginWithPhoneResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/login/phone',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * Exchange a refresh token for a new token pair
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1RefreshTokenResponse A successful response.
 * @throws ApiError
 */
export const userServiceRefreshToken = (data: UserServiceRefreshTokenData): CancelablePromise<UserServiceRefreshTokenResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/login/refresh-token',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * Send password recovery email with a reset link
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1RecoverPasswordResponse A successful response.
 * @throws ApiError
 */
export const userServiceRecoverPassword = (data: UserServiceRecoverPasswordData): CancelablePromise<UserServiceRecoverPasswordResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/password-recovery',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * Reset password using a token from email link
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1ResetPasswordResponse A successful response.
 * @throws ApiError
 */
export const userServiceResetPassword = (data: UserServiceResetPasswordData): CancelablePromise<UserServiceResetPasswordResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/reset-password',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @returns v1GetUserResponse A successful response.
 * @throws ApiError
 */
export const userServiceGetUser = (): CancelablePromise<UserServiceGetUserResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/v1/user',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1CreateUserResponse A successful response.
 * @throws ApiError
 */
export const userServiceCreateUser = (data: UserServiceCreateUserData): CancelablePromise<UserServiceCreateUserResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1UpdateUserResponse A successful response.
 * @throws ApiError
 */
export const userServiceUpdateUser = (data: UserServiceUpdateUserData): CancelablePromise<UserServiceUpdateUserResponse> => {
    return __request(OpenAPI, {
        method: 'PUT',
        url: '/v1/user',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1AddEmailResponse A successful response.
 * @throws ApiError
 */
export const userServiceAddEmail = (data: UserServiceAddEmailData): CancelablePromise<UserServiceAddEmailResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/add-email',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1AddPhoneNumberResponse A successful response.
 * @throws ApiError
 */
export const userServiceAddPhoneNumber = (data: UserServiceAddPhoneNumberData): CancelablePromise<UserServiceAddPhoneNumberResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/add-phone',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1RegisterPhoneUserResponse A successful response.
 * @throws ApiError
 */
export const userServiceRegisterPhoneUser = (data: UserServiceRegisterPhoneUserData): CancelablePromise<UserServiceRegisterPhoneUserResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/register-phone',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1RequestPhoneOTPResponse A successful response.
 * @throws ApiError
 */
export const userServiceRequestPhoneOtp = (data: UserServiceRequestPhoneOtpData): CancelablePromise<UserServiceRequestPhoneOtpResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/request-phone-otp',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1ResendEmailVerificationResponse A successful response.
 * @throws ApiError
 */
export const userServiceResendEmailVerification = (data: UserServiceResendEmailVerificationData): CancelablePromise<UserServiceResendEmailVerificationResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/resend-email',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1VerifyAddEmailOTPResponse A successful response.
 * @throws ApiError
 */
export const userServiceVerifyAddEmailOtp = (data: UserServiceVerifyAddEmailOtpData): CancelablePromise<UserServiceVerifyAddEmailOtpResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/verify-add-email',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1VerifyAddPhoneOTPResponse A successful response.
 * @throws ApiError
 */
export const userServiceVerifyAddPhoneOtp = (data: UserServiceVerifyAddPhoneOtpData): CancelablePromise<UserServiceVerifyAddPhoneOtpResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/verify-add-phone',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * Verify email using OTP code
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1VerifyEmailOTPResponse A successful response.
 * @throws ApiError
 */
export const userServiceVerifyEmailOtp = (data: UserServiceVerifyEmailOtpData): CancelablePromise<UserServiceVerifyEmailOtpResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/verify-email',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1VerifyPhoneOTPResponse A successful response.
 * @throws ApiError
 */
export const userServiceVerifyPhoneOtp = (data: UserServiceVerifyPhoneOtpData): CancelablePromise<UserServiceVerifyPhoneOtpResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/user/verify-phone-otp',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.offset
 * @param data.limit
 * @returns v1ListUsersResponse A successful response.
 * @throws ApiError
 */
export const userServiceListUsers = (data: UserServiceListUsersData = {}): CancelablePromise<UserServiceListUsersResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/v1/users',
        query: {
            offset: data.offset,
            limit: data.limit
        },
        errors: {
            default: 'An unexpected error response.'
        }
    });
};