// This file is auto-generated by @hey-api/openapi-ts

export type protobufAny = {
    '@type'?: string;
    [key: string]: (unknown | string) | undefined;
};

export type rpcStatus = {
    code?: number;
    message?: string;
    details?: Array<protobufAny>;
};

export type v1AddEmailRequest = {
    email?: string;
};

export type v1AddEmailResponse = {
    success?: boolean;
    message?: string;
};

export type v1AddPhoneNumberRequest = {
    phoneNumber?: string;
    region?: string;
};

export type v1AddPhoneNumberResponse = {
    success?: boolean;
    message?: string;
};

export type v1CreateUserRequest = {
    email?: string;
    fullName?: string;
    password?: string;
    roles?: Array<(string)>;
    isActive?: boolean;
};

export type v1CreateUserResponse = {
    user?: v1User;
};

export type v1GetUserResponse = {
    user?: v1User;
};

export type v1ListUsersResponse = {
    users?: Array<v1User>;
    total?: number;
};

export type v1LoginUserRequest = {
    username?: string;
    password?: string;
};

export type v1LoginUserResponse = {
    accessToken?: string;
    refreshToken?: string;
    expiresAt?: string;
    refreshExpiresAt?: string;
    tokenType?: string;
};

export type v1LoginWithPhoneRequest = {
    phoneNumber?: string;
    otpCode?: string;
    region?: string;
};

export type v1LoginWithPhoneResponse = {
    accessToken?: string;
    refreshToken?: string;
    expiresAt?: string;
    refreshExpiresAt?: string;
    tokenType?: string;
};

export type v1RecoverPasswordRequest = {
    email?: string;
};

export type v1RecoverPasswordResponse = {
    success?: boolean;
    message?: string;
};

export type v1RefreshTokenRequest = {
    refreshToken?: string;
};

export type v1RefreshTokenResponse = {
    accessToken?: string;
    expiresAt?: string;
};

export type v1RegisterPhoneUserRequest = {
    phoneNumber?: string;
    fullName?: string;
    region?: string;
};

export type v1RegisterPhoneUserResponse = {
    user?: v1User;
};

export type v1RequestPhoneOTPRequest = {
    phoneNumber?: string;
    region?: string;
};

export type v1RequestPhoneOTPResponse = {
    success?: boolean;
    message?: string;
};

export type v1ResendEmailVerificationRequest = {
    email?: string;
};

export type v1ResendEmailVerificationResponse = {
    success?: boolean;
    message?: string;
};

export type v1ResetPasswordRequest = {
    token?: string;
    newPassword?: string;
};

export type v1ResetPasswordResponse = {
    success?: boolean;
    message?: string;
};

export type v1UpdateUserRequest = {
    fullName?: string;
    previousPassword?: string;
    password?: string;
};

export type v1UpdateUserResponse = {
    user?: v1User;
};

export type v1User = {
    id?: string;
    email?: string;
    phoneNumber?: string;
    fullName?: string;
    isActive?: boolean;
    isEmailVerified?: boolean;
    isPhoneVerified?: boolean;
    createdAt?: string;
    updatedAt?: string;
    roles?: Array<(string)>;
};

export type v1VerifyAddEmailOTPRequest = {
    otpCode?: string;
};

export type v1VerifyAddEmailOTPResponse = {
    success?: boolean;
    message?: string;
};

export type v1VerifyAddPhoneOTPRequest = {
    otpCode?: string;
    region?: string;
};

export type v1VerifyAddPhoneOTPResponse = {
    success?: boolean;
    message?: string;
};

export type v1VerifyEmailOTPRequest = {
    email?: string;
    otpCode?: string;
};

export type v1VerifyEmailOTPResponse = {
    success?: boolean;
    message?: string;
};

export type v1VerifyPhoneOTPRequest = {
    phoneNumber?: string;
    otpCode?: string;
    region?: string;
};

export type v1VerifyPhoneOTPResponse = {
    success?: boolean;
    message?: string;
};

export type UserServiceLoginUserData = {
    requestBody: v1LoginUserRequest;
};

export type UserServiceLoginUserResponse = (v1LoginUserResponse);

export type UserServiceLoginWithPhoneData = {
    requestBody: v1LoginWithPhoneRequest;
};

export type UserServiceLoginWithPhoneResponse = (v1LoginWithPhoneResponse);

export type UserServiceRefreshTokenData = {
    requestBody: v1RefreshTokenRequest;
};

export type UserServiceRefreshTokenResponse = (v1RefreshTokenResponse);

export type UserServiceRecoverPasswordData = {
    requestBody: v1RecoverPasswordRequest;
};

export type UserServiceRecoverPasswordResponse = (v1RecoverPasswordResponse);

export type UserServiceResetPasswordData = {
    requestBody: v1ResetPasswordRequest;
};

export type UserServiceResetPasswordResponse = (v1ResetPasswordResponse);

export type UserServiceGetUserResponse = (v1GetUserResponse);

export type UserServiceCreateUserData = {
    requestBody: v1CreateUserRequest;
};

export type UserServiceCreateUserResponse = (v1CreateUserResponse);

export type UserServiceUpdateUserData = {
    requestBody: v1UpdateUserRequest;
};

export type UserServiceUpdateUserResponse = (v1UpdateUserResponse);

export type UserServiceAddEmailData = {
    requestBody: v1AddEmailRequest;
};

export type UserServiceAddEmailResponse = (v1AddEmailResponse);

export type UserServiceAddPhoneNumberData = {
    requestBody: v1AddPhoneNumberRequest;
};

export type UserServiceAddPhoneNumberResponse = (v1AddPhoneNumberResponse);

export type UserServiceRegisterPhoneUserData = {
    requestBody: v1RegisterPhoneUserRequest;
};

export type UserServiceRegisterPhoneUserResponse = (v1RegisterPhoneUserResponse);

export type UserServiceRequestPhoneOtpData = {
    requestBody: v1RequestPhoneOTPRequest;
};

export type UserServiceRequestPhoneOtpResponse = (v1RequestPhoneOTPResponse);

export type UserServiceResendEmailVerificationData = {
    requestBody: v1ResendEmailVerificationRequest;
};

export type UserServiceResendEmailVerificationResponse = (v1ResendEmailVerificationResponse);

export type UserServiceVerifyAddEmailOtpData = {
    requestBody: v1VerifyAddEmailOTPRequest;
};

export type UserServiceVerifyAddEmailOtpResponse = (v1VerifyAddEmailOTPResponse);

export type UserServiceVerifyAddPhoneOtpData = {
    requestBody: v1VerifyAddPhoneOTPRequest;
};

export type UserServiceVerifyAddPhoneOtpResponse = (v1VerifyAddPhoneOTPResponse);

export type UserServiceVerifyEmailOtpData = {
    requestBody: v1VerifyEmailOTPRequest;
};

export type UserServiceVerifyEmailOtpResponse = (v1VerifyEmailOTPResponse);

export type UserServiceVerifyPhoneOtpData = {
    requestBody: v1VerifyPhoneOTPRequest;
};

export type UserServiceVerifyPhoneOtpResponse = (v1VerifyPhoneOTPResponse);

export type UserServiceListUsersData = {
    limit?: number;
    offset?: number;
};

export type UserServiceListUsersResponse = (v1ListUsersResponse);