// This file is auto-generated by @hey-api/openapi-ts

export const OAuthServiceHandleOAuthCallbackBodySchema = {
    type: 'object',
    properties: {
        code: {
            type: 'string'
        }
    }
} as const;

export const protobufAnySchema = {
    type: 'object',
    properties: {
        '@type': {
            type: 'string'
        }
    },
    additionalProperties: {}
} as const;

export const rpcStatusSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        message: {
            type: 'string'
        },
        details: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/protobufAny'
            }
        }
    }
} as const;

export const v1GetOAuthURLResponseSchema = {
    type: 'object',
    properties: {
        url: {
            type: 'string'
        },
        state: {
            type: 'string'
        }
    }
} as const;

export const v1HandleOAuthCallbackResponseSchema = {
    type: 'object',
    properties: {
        user: {
            '$ref': '#/components/schemas/v1User'
        },
        accessToken: {
            type: 'string',
            title: 'JWT or session token'
        },
        refreshToken: {
            type: 'string',
            title: 'Optional refresh token'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        },
        refreshExpiresAt: {
            type: 'string',
            format: 'date-time'
        },
        isNewUser: {
            type: 'boolean'
        }
    }
} as const;

export const v1UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        phoneNumber: {
            type: 'string'
        },
        fullName: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        isEmailVerified: {
            type: 'boolean'
        },
        isPhoneVerified: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;