// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { OauthServiceGetOauthUrlData, OauthServiceGetOauthUrlResponse, OauthServiceHandleOauthCallbackData, OauthServiceHandleOauthCallbackResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.provider
 * @returns v1GetOAuthURLResponse A successful response.
 * @throws ApiError
 */
export const oauthServiceGetOauthUrl = (data: OauthServiceGetOauthUrlData): CancelablePromise<OauthServiceGetOauthUrlResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/v1/oauth/{provider}',
        path: {
            provider: data.provider
        },
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.provider
 * @param data.requestBody
 * @returns v1HandleOAuthCallbackResponse A successful response.
 * @throws ApiError
 */
export const oauthServiceHandleOauthCallback = (data: OauthServiceHandleOauthCallbackData): CancelablePromise<OauthServiceHandleOauthCallbackResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/oauth/{provider}/callback',
        path: {
            provider: data.provider
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};