// This file is auto-generated by @hey-api/openapi-ts

export type OAuthServiceHandleOAuthCallbackBody = {
  code?: string
}

export type protobufAny = {
  "@type"?: string
  [key: string]: (unknown | string) | undefined
}

export type rpcStatus = {
  code?: number
  message?: string
  details?: Array<protobufAny>
}

export type v1GetOAuthURLResponse = {
  url?: string
  state?: string
}

export type v1HandleOAuthCallbackResponse = {
  user?: v1User
  accessToken?: string
  refreshToken?: string
  expiresAt?: string
  refreshExpiresAt?: string
  isNewUser?: boolean
}

export type v1User = {
  id?: string
  email?: string
  phoneNumber?: string
  fullName?: string
  isActive?: boolean
  isEmailVerified?: boolean
  isPhoneVerified?: boolean
  createdAt?: string
  updatedAt?: string
  roles?: Array<string>
}

export type OauthServiceGetOauthUrlData = {
  provider: string
}

export type OauthServiceGetOauthUrlResponse = v1GetOAuthURLResponse

export type OauthServiceHandleOauthCallbackData = {
  provider: string
  requestBody: OAuthServiceHandleOAuthCallbackBody
}

export type OauthServiceHandleOauthCallbackResponse =
  v1HandleOAuthCallbackResponse
