// This file is auto-generated by @hey-api/openapi-ts

export const DataSourceServiceTestConnectionBodySchema = {
  type: "object",
} as const

export const protobufAnySchema = {
  type: "object",
  properties: {
    "@type": {
      type: "string",
    },
  },
  additionalProperties: {},
} as const

export const rpcStatusSchema = {
  type: "object",
  properties: {
    code: {
      type: "integer",
      format: "int32",
    },
    message: {
      type: "string",
    },
    details: {
      type: "array",
      items: {
        $ref: "#/components/schemas/protobufAny",
      },
    },
  },
} as const

export const v1AskQuestionRequestSchema = {
  type: "object",
  properties: {
    dataSourceId: {
      type: "string",
    },
    question: {
      type: "string",
    },
  },
} as const

export const v1AskQuestionResponseSchema = {
  type: "object",
  properties: {
    answer: {
      type: "string",
    },
    sql: {
      type: "string",
    },
    resultJson: {
      type: "string",
    },
  },
} as const

export const v1CreateDataSourceRequestSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    type: {
      type: "string",
      title: "postgres, mysql",
    },
    host: {
      type: "string",
    },
    port: {
      type: "integer",
      format: "int32",
    },
    databaseName: {
      type: "string",
    },
    username: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
} as const

export const v1CreateDataSourceResponseSchema = {
  type: "object",
  properties: {
    dataSource: {
      $ref: "#/components/schemas/v1DataSource",
    },
  },
} as const

export const v1DataSourceSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    type: {
      type: "string",
    },
    host: {
      type: "string",
    },
    port: {
      type: "integer",
      format: "int32",
    },
    databaseName: {
      type: "string",
    },
    username: {
      type: "string",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const

export const v1IntrospectSchemaResponseSchema = {
  type: "object",
  properties: {
    schemaJson: {
      type: "string",
    },
    summary: {
      type: "string",
    },
  },
} as const

export const v1SetAICredentialRequestSchema = {
  type: "object",
  properties: {
    provider: {
      type: "string",
    },
    apiKey: {
      type: "string",
    },
  },
} as const

export const v1TestConnectionResponseSchema = {
  type: "object",
  properties: {
    ok: {
      type: "boolean",
    },
    message: {
      type: "string",
    },
  },
} as const
