// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  DataSourceServiceAskQuestionData,
  DataSourceServiceAskQuestionResponse,
  DataSourceServiceCreateDataSourceData,
  DataSourceServiceCreateDataSourceResponse,
  DataSourceServiceIntrospectSchemaData,
  DataSourceServiceIntrospectSchemaResponse,
  DataSourceServiceSetAiCredentialData,
  DataSourceServiceSetAiCredentialResponse,
  DataSourceServiceTestConnectionData,
  DataSourceServiceTestConnectionResponse,
} from "./types.gen"

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1AskQuestionResponse A successful response.
 * @throws ApiError
 */
export const dataSourceServiceAskQuestion = (
  data: DataSourceServiceAskQuestionData,
): CancelablePromise<DataSourceServiceAskQuestionResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/v1/ai/ask",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      default: "An unexpected error response.",
    },
  })
}

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown A successful response.
 * @throws ApiError
 */
export const dataSourceServiceSetAiCredential = (
  data: DataSourceServiceSetAiCredentialData,
): CancelablePromise<DataSourceServiceSetAiCredentialResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/v1/ai/credentials",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      default: "An unexpected error response.",
    },
  })
}

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1CreateDataSourceResponse A successful response.
 * @throws ApiError
 */
export const dataSourceServiceCreateDataSource = (
  data: DataSourceServiceCreateDataSourceData,
): CancelablePromise<DataSourceServiceCreateDataSourceResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/v1/datasources",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      default: "An unexpected error response.",
    },
  })
}

/**
 * @param data The data for the request.
 * @param data.id
 * @returns v1IntrospectSchemaResponse A successful response.
 * @throws ApiError
 */
export const dataSourceServiceIntrospectSchema = (
  data: DataSourceServiceIntrospectSchemaData,
): CancelablePromise<DataSourceServiceIntrospectSchemaResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/v1/datasources/{id}/schema",
    path: {
      id: data.id,
    },
    errors: {
      default: "An unexpected error response.",
    },
  })
}

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns v1TestConnectionResponse A successful response.
 * @throws ApiError
 */
export const dataSourceServiceTestConnection = (
  data: DataSourceServiceTestConnectionData,
): CancelablePromise<DataSourceServiceTestConnectionResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/v1/datasources/{id}/test",
    path: {
      id: data.id,
    },
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      default: "An unexpected error response.",
    },
  })
}
