// This file is auto-generated by @hey-api/openapi-ts

export type DataSourceServiceTestConnectionBody = {
    [key: string]: unknown;
};

export type protobufAny = {
    '@type'?: string;
    [key: string]: (unknown | string) | undefined;
};

export type rpcStatus = {
    code?: number;
    message?: string;
    details?: Array<protobufAny>;
};

export type v1AskQuestionRequest = {
    dataSourceId?: string;
    question?: string;
};

export type v1AskQuestionResponse = {
    answer?: string;
    sql?: string;
    resultJson?: string;
};

export type v1CreateDataSourceRequest = {
    name?: string;
    type?: string;
    host?: string;
    port?: number;
    databaseName?: string;
    username?: string;
    password?: string;
};

export type v1CreateDataSourceResponse = {
    dataSource?: v1DataSource;
};

export type v1DataSource = {
    id?: string;
    name?: string;
    type?: string;
    host?: string;
    port?: number;
    databaseName?: string;
    username?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type v1IntrospectSchemaResponse = {
    schemaJson?: string;
    summary?: string;
};

export type v1SetAICredentialRequest = {
    provider?: string;
    apiKey?: string;
};

export type v1TestConnectionResponse = {
    ok?: boolean;
    message?: string;
};

export type DataSourceServiceAskQuestionData = {
    requestBody: v1AskQuestionRequest;
};

export type DataSourceServiceAskQuestionResponse = (v1AskQuestionResponse);

export type DataSourceServiceSetAiCredentialData = {
    requestBody: v1SetAICredentialRequest;
};

export type DataSourceServiceSetAiCredentialResponse = ({
    [key: string]: unknown;
});

export type DataSourceServiceCreateDataSourceData = {
    requestBody: v1CreateDataSourceRequest;
};

export type DataSourceServiceCreateDataSourceResponse = (v1CreateDataSourceResponse);

export type DataSourceServiceIntrospectSchemaData = {
    id: string;
};

export type DataSourceServiceIntrospectSchemaResponse = (v1IntrospectSchemaResponse);

export type DataSourceServiceTestConnectionData = {
    id: string;
    requestBody: DataSourceServiceTestConnectionBody;
};

export type DataSourceServiceTestConnectionResponse = (v1TestConnectionResponse);