// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthAccount struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    pgtype.Text        `json:"access_token"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PhoneNumber     pgtype.Text        `json:"phone_number"`
	FullName        pgtype.Text        `json:"full_name"`
	HashedPassword  pgtype.Text        `json:"hashed_password"`
	IsActive        bool               `json:"is_active"`
	IsSuperuser     bool               `json:"is_superuser"`
	IsEmailVerified bool               `json:"is_email_verified"`
	IsPhoneVerified bool               `json:"is_phone_verified"`
	IsTotpEnabled   bool               `json:"is_totp_enabled"`
	TotpSecret      pgtype.Text        `json:"totp_secret"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
}

type UserRole struct {
	UserID     uuid.UUID          `json:"user_id"`
	RoleID     int32              `json:"role_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type VerificationCode struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	VerificationCode string             `json:"verification_code"`
	VerificationType string             `json:"verification_type"`
	ExtraMetadata    pgtype.JSONBCodec  `json:"extra_metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	UsedAt           pgtype.Timestamptz `json:"used_at"`
}
