// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOAuthAccount(ctx context.Context, arg DeleteOAuthAccountParams) error
	DeleteOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) error
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetOAuthAccountByID(ctx context.Context, id uuid.UUID) (OauthAccount, error)
	GetOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
	UpdateOAuthAccountTokens(ctx context.Context, arg UpdateOAuthAccountTokensParams) (OauthAccount, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
