// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_role (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID int32     `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_account (
    user_id, provider, provider_user_id, access_token, refresh_token, token_expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, provider, provider_user_id, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    pgtype.Text        `json:"access_token"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
    email, phone_number, full_name, hashed_password
) VALUES (
    $1, $2, $3, $4
) RETURNING id, email, phone_number, full_name, hashed_password, is_active, is_superuser, is_email_verified, is_phone_verified, is_totp_enabled, totp_secret, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	Email          string      `json:"email"`
	PhoneNumber    pgtype.Text `json:"phone_number"`
	FullName       pgtype.Text `json:"full_name"`
	HashedPassword pgtype.Text `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PhoneNumber,
		arg.FullName,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FullName,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_user_id, access_token, refresh_token, token_expires_at, created_at, updated_at FROM oauth_account
WHERE provider = $1 AND provider_user_id = $2 LIMIT 1
`

type GetOAuthAccountParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone_number, full_name, hashed_password, is_active, is_superuser, is_email_verified, is_phone_verified, is_totp_enabled, totp_secret, created_at, updated_at, last_login_at FROM "user"
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FullName,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone_number, full_name, hashed_password, is_active, is_superuser, is_email_verified, is_phone_verified, is_totp_enabled, totp_secret, created_at, updated_at, last_login_at FROM "user"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FullName,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description, r.created_at, r.updated_at FROM role r
JOIN user_role ur ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET 
    email = COALESCE($2, email),
    phone_number = COALESCE($3, phone_number),
    full_name = COALESCE($4, full_name),
    hashed_password = COALESCE($5, hashed_password),
    is_active = COALESCE($6, is_active),
    updated_at = now()
WHERE id = $1
RETURNING id, email, phone_number, full_name, hashed_password, is_active, is_superuser, is_email_verified, is_phone_verified, is_totp_enabled, totp_secret, created_at, updated_at, last_login_at
`

type UpdateUserParams struct {
	ID             uuid.UUID   `json:"id"`
	Email          string      `json:"email"`
	PhoneNumber    pgtype.Text `json:"phone_number"`
	FullName       pgtype.Text `json:"full_name"`
	HashedPassword pgtype.Text `json:"hashed_password"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.PhoneNumber,
		arg.FullName,
		arg.HashedPassword,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FullName,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
