// This file is auto-generated by @hey-api/openapi-ts

export const WeddingServiceAddGuestBodySchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        contact: {
            type: 'string'
        },
        rsvpStatus: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const WeddingServicePublishBodySchema = {
    type: 'object'
} as const;

export const WeddingServiceSetDomainBodySchema = {
    type: 'object',
    properties: {
        domain: {
            type: 'string'
        }
    }
} as const;

export const WeddingServiceSetSlugBodySchema = {
    type: 'object',
    properties: {
        slug: {
            type: 'string'
        }
    }
} as const;

export const WeddingServiceSetTemplateBodySchema = {
    type: 'object',
    properties: {
        templateId: {
            type: 'string'
        }
    }
} as const;

export const WeddingServiceUpdateConfigBodySchema = {
    type: 'object',
    properties: {
        configJson: {
            type: 'string'
        }
    }
} as const;

export const WeddingServiceUpdateGuestBodySchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        contact: {
            type: 'string'
        },
        rsvpStatus: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const protobufAnySchema = {
    type: 'object',
    properties: {
        '@type': {
            type: 'string'
        }
    },
    additionalProperties: {}
} as const;

export const rpcStatusSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        message: {
            type: 'string'
        },
        details: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/protobufAny'
            }
        }
    }
} as const;

export const v1CreateWeddingRequestSchema = {
    type: 'object',
    properties: {
        templateId: {
            type: 'string'
        },
        configJson: {
            type: 'string'
        }
    }
} as const;

export const v1GuestSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        weddingId: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        contact: {
            type: 'string'
        },
        rsvpStatus: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'int64'
        }
    }
} as const;

export const v1GuestResponseSchema = {
    type: 'object',
    properties: {
        guest: {
            '$ref': '#/components/schemas/v1Guest'
        }
    }
} as const;

export const v1GuestsResponseSchema = {
    type: 'object',
    properties: {
        guests: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/v1Guest'
            }
        }
    }
} as const;

export const v1WeddingSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        templateId: {
            type: 'string'
        },
        paymentId: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        customDomain: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        configJson: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'int64'
        }
    }
} as const;

export const v1WeddingResponseSchema = {
    type: 'object',
    properties: {
        wedding: {
            '$ref': '#/components/schemas/v1Wedding'
        }
    }
} as const;