// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { WeddingServiceCreateWeddingData, WeddingServiceCreateWeddingResponse, WeddingServiceGetWeddingData, WeddingServiceGetWeddingResponse, WeddingServiceUpdateConfigData, WeddingServiceUpdateConfigResponse, WeddingServiceSetDomainData, WeddingServiceSetDomainResponse, WeddingServiceListGuestsData, WeddingServiceListGuestsResponse, WeddingServiceAddGuestData, WeddingServiceAddGuestResponse, WeddingServiceDeleteGuestData, WeddingServiceDeleteGuestResponse, WeddingServiceUpdateGuestData, WeddingServiceUpdateGuestResponse, WeddingServicePublishData, WeddingServicePublishResponse, WeddingServiceSetSlugData, WeddingServiceSetSlugResponse, WeddingServiceSetTemplateData, WeddingServiceSetTemplateResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns v1WeddingResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceCreateWedding = (data: WeddingServiceCreateWeddingData): CancelablePromise<WeddingServiceCreateWeddingResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/weddings',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns v1WeddingResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceGetWedding = (data: WeddingServiceGetWeddingData): CancelablePromise<WeddingServiceGetWeddingResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/v1/weddings/{id}',
        path: {
            id: data.id
        },
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns v1WeddingResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceUpdateConfig = (data: WeddingServiceUpdateConfigData): CancelablePromise<WeddingServiceUpdateConfigResponse> => {
    return __request(OpenAPI, {
        method: 'PUT',
        url: '/v1/weddings/{id}/config',
        path: {
            id: data.id
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns v1WeddingResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceSetDomain = (data: WeddingServiceSetDomainData): CancelablePromise<WeddingServiceSetDomainResponse> => {
    return __request(OpenAPI, {
        method: 'PUT',
        url: '/v1/weddings/{id}/domain',
        path: {
            id: data.id
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns v1GuestsResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceListGuests = (data: WeddingServiceListGuestsData): CancelablePromise<WeddingServiceListGuestsResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/v1/weddings/{id}/guests',
        path: {
            id: data.id
        },
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns v1GuestResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceAddGuest = (data: WeddingServiceAddGuestData): CancelablePromise<WeddingServiceAddGuestResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/weddings/{id}/guests',
        path: {
            id: data.id
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.guestId
 * @returns unknown A successful response.
 * @throws ApiError
 */
export const weddingServiceDeleteGuest = (data: WeddingServiceDeleteGuestData): CancelablePromise<WeddingServiceDeleteGuestResponse> => {
    return __request(OpenAPI, {
        method: 'DELETE',
        url: '/v1/weddings/{id}/guests/{guestId}',
        path: {
            id: data.id,
            guestId: data.guestId
        },
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.guestId
 * @param data.requestBody
 * @returns v1GuestResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceUpdateGuest = (data: WeddingServiceUpdateGuestData): CancelablePromise<WeddingServiceUpdateGuestResponse> => {
    return __request(OpenAPI, {
        method: 'PUT',
        url: '/v1/weddings/{id}/guests/{guestId}',
        path: {
            id: data.id,
            guestId: data.guestId
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns v1WeddingResponse A successful response.
 * @throws ApiError
 */
export const weddingServicePublish = (data: WeddingServicePublishData): CancelablePromise<WeddingServicePublishResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/weddings/{id}/publish',
        path: {
            id: data.id
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns v1WeddingResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceSetSlug = (data: WeddingServiceSetSlugData): CancelablePromise<WeddingServiceSetSlugResponse> => {
    return __request(OpenAPI, {
        method: 'PUT',
        url: '/v1/weddings/{id}/slug',
        path: {
            id: data.id
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns v1WeddingResponse A successful response.
 * @throws ApiError
 */
export const weddingServiceSetTemplate = (data: WeddingServiceSetTemplateData): CancelablePromise<WeddingServiceSetTemplateResponse> => {
    return __request(OpenAPI, {
        method: 'PUT',
        url: '/v1/weddings/{id}/template',
        path: {
            id: data.id
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            default: 'An unexpected error response.'
        }
    });
};