// This file is auto-generated by @hey-api/openapi-ts

export type protobufAny = {
    '@type'?: string;
    [key: string]: (unknown | string) | undefined;
};

export type rpcStatus = {
    code?: number;
    message?: string;
    details?: Array<protobufAny>;
};

export type v1CreateWeddingRequest = {
    templateId?: string;
    configJson?: string;
};

export type v1Guest = {
    id?: string;
    weddingId?: string;
    name?: string;
    contact?: string;
    rsvpStatus?: string;
    message?: string;
    createdAt?: string;
};

export type v1GuestResponse = {
    guest?: v1Guest;
};

export type v1GuestsResponse = {
    guests?: Array<v1Guest>;
};

export type v1Wedding = {
    id?: string;
    userId?: string;
    templateId?: string;
    paymentId?: string;
    status?: string;
    customDomain?: string;
    slug?: string;
    configJson?: string;
    createdAt?: string;
};

export type v1WeddingResponse = {
    wedding?: v1Wedding;
};

export type WeddingServiceAddGuestBody = {
    name?: string;
    contact?: string;
    rsvpStatus?: string;
    message?: string;
};

export type WeddingServicePublishBody = {
    [key: string]: unknown;
};

export type WeddingServiceSetDomainBody = {
    domain?: string;
};

export type WeddingServiceSetSlugBody = {
    slug?: string;
};

export type WeddingServiceSetTemplateBody = {
    templateId?: string;
};

export type WeddingServiceUpdateConfigBody = {
    configJson?: string;
};

export type WeddingServiceUpdateGuestBody = {
    name?: string;
    contact?: string;
    rsvpStatus?: string;
    message?: string;
};

export type WeddingServiceCreateWeddingData = {
    requestBody: v1CreateWeddingRequest;
};

export type WeddingServiceCreateWeddingResponse = (v1WeddingResponse);

export type WeddingServiceGetWeddingData = {
    id: string;
};

export type WeddingServiceGetWeddingResponse = (v1WeddingResponse);

export type WeddingServiceUpdateConfigData = {
    id: string;
    requestBody: WeddingServiceUpdateConfigBody;
};

export type WeddingServiceUpdateConfigResponse = (v1WeddingResponse);

export type WeddingServiceSetDomainData = {
    id: string;
    requestBody: WeddingServiceSetDomainBody;
};

export type WeddingServiceSetDomainResponse = (v1WeddingResponse);

export type WeddingServiceListGuestsData = {
    id: string;
};

export type WeddingServiceListGuestsResponse = (v1GuestsResponse);

export type WeddingServiceAddGuestData = {
    id: string;
    requestBody: WeddingServiceAddGuestBody;
};

export type WeddingServiceAddGuestResponse = (v1GuestResponse);

export type WeddingServiceDeleteGuestData = {
    guestId: string;
    id: string;
};

export type WeddingServiceDeleteGuestResponse = ({
    [key: string]: unknown;
});

export type WeddingServiceUpdateGuestData = {
    guestId: string;
    id: string;
    requestBody: WeddingServiceUpdateGuestBody;
};

export type WeddingServiceUpdateGuestResponse = (v1GuestResponse);

export type WeddingServicePublishData = {
    id: string;
    requestBody: WeddingServicePublishBody;
};

export type WeddingServicePublishResponse = (v1WeddingResponse);

export type WeddingServiceSetSlugData = {
    id: string;
    requestBody: WeddingServiceSetSlugBody;
};

export type WeddingServiceSetSlugResponse = (v1WeddingResponse);

export type WeddingServiceSetTemplateData = {
    id: string;
    requestBody: WeddingServiceSetTemplateBody;
};

export type WeddingServiceSetTemplateResponse = (v1WeddingResponse);