"""Initialize models

Revision ID: e2412789c190
Revises: 
Create Date: 2023-11-24 22:55:43.195942

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg

# revision identifiers, used by Alembic.
revision = "e2412789c190"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Ensure pgcrypto extension if using gen_random_uuid (optional)
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")


    # role table
    op.create_table(
        'role',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(length=50), nullable=False, unique=True),
        sa.Column('description', sa.String(length=255), nullable=True)
    )

    # user table
    op.create_table(
        'user',
        sa.Column('id', pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone_number', sa.String(length=32), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('is_phone_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()')),
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_index('ix_user_phone', 'user', ['phone_number'], unique=True)

    # pending_user table
    op.create_table(
        'pending_user',
        sa.Column('id', pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone_number', sa.String(length=32), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('verification_code', sa.String(length=64), nullable=False),
        sa.Column('verification_type', sa.String(length=16), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()')),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False)
    )

    # association table user_role
    op.create_table(
        'user_role',
        sa.Column('user_id', pg.UUID(as_uuid=True), sa.ForeignKey('user.id', ondelete='CASCADE'), primary_key=True, nullable=False),
        sa.Column('role_id', sa.Integer(), sa.ForeignKey('role.id', ondelete='CASCADE'), primary_key=True, nullable=False),
    )

    # oauth_account table
    op.create_table(
        'oauth_account',
        sa.Column('id', pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('user_id', pg.UUID(as_uuid=True), sa.ForeignKey('user.id', ondelete='CASCADE'), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('provider_user_id', sa.String(length=255), nullable=False),
        sa.Column('access_token', sa.String(), nullable=True)
    )

    # seed roles
    op.execute("INSERT INTO role (name, description) VALUES ('customer','Default customer role') ON CONFLICT DO NOTHING;")
    op.execute("INSERT INTO role (name, description) VALUES ('salon_owner','Beauty salon owner') ON CONFLICT DO NOTHING;")
    op.execute("INSERT INTO role (name, description) VALUES ('employee','Salon employee') ON CONFLICT DO NOTHING;")

    op.create_table(
        "item",
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("owner_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),  
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_account')
    op.drop_table('user_role')
    op.drop_table('pending_user')
    op.drop_index('ix_user_phone', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table("item")
    # ### end Alembic commands ###
