/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WebistreamImport } from './routes/webistream'
import { Route as VerifyPhoneImport } from './routes/verify-phone'
import { Route as VerifyEmailImport } from './routes/verify-email'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as OauthCallbackImport } from './routes/oauth-callback'
import { Route as LoginImport } from './routes/login'
import { Route as ChooseRoleImport } from './routes/choose-role'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as WebinarsIndexImport } from './routes/webinars/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as WebinarsManageImport } from './routes/webinars/manage'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as WebistreamPagePageKeyImport } from './routes/webistream/page/$pageKey'

// Create/Update Routes

const WebistreamRoute = WebistreamImport.update({
  path: '/webistream',
  getParentRoute: () => rootRoute,
} as any)

const VerifyPhoneRoute = VerifyPhoneImport.update({
  path: '/verify-phone',
  getParentRoute: () => rootRoute,
} as any)

const VerifyEmailRoute = VerifyEmailImport.update({
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const OauthCallbackRoute = OauthCallbackImport.update({
  path: '/oauth-callback',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ChooseRoleRoute = ChooseRoleImport.update({
  path: '/choose-role',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WebinarsIndexRoute = WebinarsIndexImport.update({
  path: '/webinars/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const WebinarsManageRoute = WebinarsManageImport.update({
  path: '/webinars/manage',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const WebistreamPagePageKeyRoute = WebistreamPagePageKeyImport.update({
  path: '/page/$pageKey',
  getParentRoute: () => WebistreamRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/choose-role': {
      preLoaderRoute: typeof ChooseRoleImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/oauth-callback': {
      preLoaderRoute: typeof OauthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/verify-email': {
      preLoaderRoute: typeof VerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/verify-phone': {
      preLoaderRoute: typeof VerifyPhoneImport
      parentRoute: typeof rootRoute
    }
    '/webistream': {
      preLoaderRoute: typeof WebistreamImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/webinars/manage': {
      preLoaderRoute: typeof WebinarsManageImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/webinars/': {
      preLoaderRoute: typeof WebinarsIndexImport
      parentRoute: typeof rootRoute
    }
    '/webistream/page/$pageKey': {
      preLoaderRoute: typeof WebistreamPagePageKeyImport
      parentRoute: typeof WebistreamImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  ChooseRoleRoute,
  LoginRoute,
  OauthCallbackRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
  VerifyEmailRoute,
  VerifyPhoneRoute,
  WebistreamRoute.addChildren([WebistreamPagePageKeyRoute]),
  WebinarsManageRoute,
  WebinarsIndexRoute,
])

/* prettier-ignore-end */
